const matches = [
  {
    grupo: "Grupo A",
    local: "Mexico",
    localScore: null,
    visitante: "Sudafrica",
    visitanteScore: null,
    fecha: "Jue, 11/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo A",
    local: "Corea del Sur",
    localScore: null,
    visitante: "Chequia",
    visitanteScore: null,
    fecha: "Vie, 12/6",
    hora: "04:00",
  },
  {
    grupo: "Grupo B",
    local: "Canada",
    localScore: null,
    visitante: "Bosnia y Herzegovina",
    visitanteScore: null,
    fecha: "Vie, 12/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo D",
    local: "Estados Unidos",
    localScore: null,
    visitante: "Paraguay",
    visitanteScore: null,
    fecha: "Sab, 13/6",
    hora: "03:00",
  },
  {
    grupo: "Grupo B",
    local: "Catar",
    localScore: null,
    visitante: "Suiza",
    visitanteScore: null,
    fecha: "Sab, 13/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo C",
    local: "Brasil",
    localScore: null,
    visitante: "Marruecos",
    visitanteScore: null,
    fecha: "Dom, 14/6",
    hora: "00:00",
  },
  {
    grupo: "Grupo C",
    local: "Haiti",
    localScore: null,
    visitante: "Escocia",
    visitanteScore: null,
    fecha: "Dom, 14/6",
    hora: "03:00",
  },
  {
    grupo: "Grupo D",
    local: "Australia",
    localScore: null,
    visitante: "Turquia",
    visitanteScore: null,
    fecha: "Dom, 14/6",
    hora: "06:00",
  },
  {
    grupo: "Grupo E",
    local: "Alemania",
    localScore: null,
    visitante: "Curazao",
    visitanteScore: null,
    fecha: "Dom, 14/6",
    hora: "19:00",
  },
  {
    grupo: "Grupo F",
    local: "Paises Bajos",
    localScore: null,
    visitante: "Japon",
    visitanteScore: null,
    fecha: "Dom, 14/6",
    hora: "22:00",
  },
  {
    grupo: "Grupo E",
    local: "Costa de Marfil",
    localScore: null,
    visitante: "Ecuador",
    visitanteScore: null,
    fecha: "Lun, 15/6",
    hora: "01:00",
  },
  {
    grupo: "Grupo F",
    local: "Suecia",
    localScore: null,
    visitante: "Tunez",
    visitanteScore: null,
    fecha: "Lun, 15/6",
    hora: "04:00",
  },
  {
    grupo: "Grupo H",
    local: "España",
    localScore: null,
    visitante: "Cabo Verde",
    visitanteScore: null,
    fecha: "Lun, 15/6",
    hora: "18:00",
  },
  {
    grupo: "Grupo G",
    local: "Belgica",
    localScore: null,
    visitante: "Egipto",
    visitanteScore: null,
    fecha: "Lun, 15/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo H",
    local: "Arabia Saudita",
    localScore: null,
    visitante: "Uruguay",
    visitanteScore: null,
    fecha: "Mar, 16/6",
    hora: "00:00",
  },
  {
    grupo: "Grupo G",
    local: "Iran",
    localScore: null,
    visitante: "Nueva Zelanda",
    visitanteScore: null,
    fecha: "Mar, 16/6",
    hora: "03:00",
  },
  {
    grupo: "Grupo I",
    local: "Francia",
    localScore: null,
    visitante: "Senegal",
    visitanteScore: null,
    fecha: "Mar, 16/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo I",
    local: "Irak",
    localScore: null,
    visitante: "Noruega",
    visitanteScore: null,
    fecha: "Mie, 17/6",
    hora: "00:00",
  },
  {
    grupo: "Grupo J",
    local: "Argentina",
    localScore: null,
    visitante: "Argelia",
    visitanteScore: null,
    fecha: "Mie, 17/6",
    hora: "03:00",
  },
  {
    grupo: "Grupo J",
    local: "Austria",
    localScore: null,
    visitante: "Jordania",
    visitanteScore: null,
    fecha: "Mie, 17/6",
    hora: "06:00",
  },
  {
    grupo: "Grupo K",
    local: "Portugal",
    localScore: null,
    visitante: "RD Congo",
    visitanteScore: null,
    fecha: "Mie, 17/6",
    hora: "19:00",
  },
  {
    grupo: "Grupo L",
    local: "Inglaterra",
    localScore: null,
    visitante: "Croacia",
    visitanteScore: null,
    fecha: "Mie, 17/6",
    hora: "22:00",
  },
  {
    grupo: "Grupo L",
    local: "Ghana",
    localScore: null,
    visitante: "Panama",
    visitanteScore: null,
    fecha: "Jue, 18/6",
    hora: "01:00",
  },
  {
    grupo: "Grupo K",
    local: "Uzbekistan",
    localScore: null,
    visitante: "Colombia",
    visitanteScore: null,
    fecha: "Jue, 18/6",
    hora: "04:00",
  },
  {
    grupo: "Grupo A",
    local: "Chequia",
    localScore: null,
    visitante: "Sudafrica",
    visitanteScore: null,
    fecha: "Jue, 18/6",
    hora: "18:00",
  },
  {
    grupo: "Grupo B",
    local: "Suiza",
    localScore: null,
    visitante: "Bosnia y Herzegovina",
    visitanteScore: null,
    fecha: "Jue, 18/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo B",
    local: "Canada",
    localScore: null,
    visitante: "Catar",
    visitanteScore: null,
    fecha: "Vie, 19/6",
    hora: "00:00",
  },
  {
    grupo: "Grupo A",
    local: "Mexico",
    localScore: null,
    visitante: "Corea del Sur",
    visitanteScore: null,
    fecha: "Vie, 19/6",
    hora: "03:00",
  },
  {
    grupo: "Grupo D",
    local: "Estados Unidos",
    localScore: null,
    visitante: "Australia",
    visitanteScore: null,
    fecha: "Vie, 19/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo C",
    local: "Escocia",
    localScore: null,
    visitante: "Marruecos",
    visitanteScore: null,
    fecha: "Sab, 20/6",
    hora: "00:00",
  },
  {
    grupo: "Grupo C",
    local: "Brasil",
    localScore: null,
    visitante: "Haiti",
    visitanteScore: null,
    fecha: "Sab, 20/6",
    hora: "02:30",
  },
  {
    grupo: "Grupo D",
    local: "Turquia",
    localScore: null,
    visitante: "Paraguay",
    visitanteScore: null,
    fecha: "Sab, 20/6",
    hora: "05:00",
  },
  {
    grupo: "Grupo F",
    local: "Paises Bajos",
    localScore: null,
    visitante: "Suecia",
    visitanteScore: null,
    fecha: "Sab, 20/6",
    hora: "19:00",
  },
  {
    grupo: "Grupo E",
    local: "Alemania",
    localScore: null,
    visitante: "Costa de Marfil",
    visitanteScore: null,
    fecha: "Sab, 20/6",
    hora: "22:00",
  },
  {
    grupo: "Grupo E",
    local: "Ecuador",
    localScore: null,
    visitante: "Curazao",
    visitanteScore: null,
    fecha: "Dom, 21/6",
    hora: "02:00",
  },
  {
    grupo: "Grupo F",
    local: "Tunez",
    localScore: null,
    visitante: "Japon",
    visitanteScore: null,
    fecha: "Dom, 21/6",
    hora: "06:00",
  },
  {
    grupo: "Grupo H",
    local: "España",
    localScore: null,
    visitante: "Arabia Saudita",
    visitanteScore: null,
    fecha: "Dom, 21/6",
    hora: "18:00",
  },
  {
    grupo: "Grupo G",
    local: "Belgica",
    localScore: null,
    visitante: "Iran",
    visitanteScore: null,
    fecha: "Dom, 21/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo H",
    local: "Uruguay",
    localScore: null,
    visitante: "Cabo Verde",
    visitanteScore: null,
    fecha: "Lun, 22/6",
    hora: "00:00",
  },
  {
    grupo: "Grupo G",
    local: "Nueva Zelanda",
    localScore: null,
    visitante: "Egipto",
    visitanteScore: null,
    fecha: "Lun, 22/6",
    hora: "03:00",
  },
  {
    grupo: "Grupo J",
    local: "Argentina",
    localScore: null,
    visitante: "Austria",
    visitanteScore: null,
    fecha: "Lun, 22/6",
    hora: "19:00",
  },
  {
    grupo: "Grupo I",
    local: "Francia",
    localScore: null,
    visitante: "Irak",
    visitanteScore: null,
    fecha: "Lun, 22/6",
    hora: "23:00",
  },
  {
    grupo: "Grupo I",
    local: "Noruega",
    localScore: null,
    visitante: "Senegal",
    visitanteScore: null,
    fecha: "Mar, 23/6",
    hora: "02:00",
  },
  {
    grupo: "Grupo J",
    local: "Jordania",
    localScore: null,
    visitante: "Argelia",
    visitanteScore: null,
    fecha: "Mar, 23/6",
    hora: "05:00",
  },
  {
    grupo: "Grupo K",
    local: "Portugal",
    localScore: null,
    visitante: "Uzbekistan",
    visitanteScore: null,
    fecha: "Mar, 23/6",
    hora: "19:00",
  },
  {
    grupo: "Grupo L",
    local: "Inglaterra",
    localScore: null,
    visitante: "Ghana",
    visitanteScore: null,
    fecha: "Mar, 23/6",
    hora: "22:00",
  },
  {
    grupo: "Grupo L",
    local: "Panama",
    localScore: null,
    visitante: "Croacia",
    visitanteScore: null,
    fecha: "Mie, 24/6",
    hora: "01:00",
  },
  {
    grupo: "Grupo K",
    local: "Colombia",
    localScore: null,
    visitante: "RD Congo",
    visitanteScore: null,
    fecha: "Mie, 24/6",
    hora: "04:00",
  },
  {
    grupo: "Grupo B",
    local: "Suiza",
    localScore: null,
    visitante: "Canada",
    visitanteScore: null,
    fecha: "Mie, 24/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo B",
    local: "Bosnia y Herzegovina",
    localScore: null,
    visitante: "Catar",
    visitanteScore: null,
    fecha: "Mie, 24/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo C",
    local: "Marruecos",
    localScore: null,
    visitante: "Haiti",
    visitanteScore: null,
    fecha: "Jue, 25/6",
    hora: "00:00",
  },
  {
    grupo: "Grupo C",
    local: "Escocia",
    localScore: null,
    visitante: "Brasil",
    visitanteScore: null,
    fecha: "Jue, 25/6",
    hora: "00:00",
  },
  {
    grupo: "Grupo A",
    local: "Sudafrica",
    localScore: null,
    visitante: "Corea del Sur",
    visitanteScore: null,
    fecha: "Jue, 25/6",
    hora: "03:00",
  },
  {
    grupo: "Grupo A",
    local: "Chequia",
    localScore: null,
    visitante: "Mexico",
    visitanteScore: null,
    fecha: "Jue, 25/6",
    hora: "03:00",
  },
  {
    grupo: "Grupo E",
    local: "Curazao",
    localScore: null,
    visitante: "Costa de Marfil",
    visitanteScore: null,
    fecha: "Jue, 25/6",
    hora: "22:00",
  },
  {
    grupo: "Grupo E",
    local: "Ecuador",
    localScore: null,
    visitante: "Alemania",
    visitanteScore: null,
    fecha: "Jue, 25/6",
    hora: "22:00",
  },
  {
    grupo: "Grupo F",
    local: "Tunez",
    localScore: null,
    visitante: "Paises Bajos",
    visitanteScore: null,
    fecha: "Vie, 26/6",
    hora: "01:00",
  },
  {
    grupo: "Grupo F",
    local: "Japon",
    localScore: null,
    visitante: "Suecia",
    visitanteScore: null,
    fecha: "Vie, 26/6",
    hora: "01:00",
  },
  {
    grupo: "Grupo D",
    local: "Turquia",
    localScore: null,
    visitante: "Estados Unidos",
    visitanteScore: null,
    fecha: "Vie, 26/6",
    hora: "04:00",
  },
  {
    grupo: "Grupo D",
    local: "Paraguay",
    localScore: null,
    visitante: "Australia",
    visitanteScore: null,
    fecha: "Vie, 26/6",
    hora: "04:00",
  },
  {
    grupo: "Grupo I",
    local: "Noruega",
    localScore: null,
    visitante: "Francia",
    visitanteScore: null,
    fecha: "Vie, 26/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo I",
    local: "Senegal",
    localScore: null,
    visitante: "Irak",
    visitanteScore: null,
    fecha: "Vie, 26/6",
    hora: "21:00",
  },
  {
    grupo: "Grupo H",
    local: "Cabo Verde",
    localScore: null,
    visitante: "Arabia Saudita",
    visitanteScore: null,
    fecha: "Sab, 27/6",
    hora: "02:00",
  },
  {
    grupo: "Grupo H",
    local: "Uruguay",
    localScore: null,
    visitante: "España",
    visitanteScore: null,
    fecha: "Sab, 27/6",
    hora: "02:00",
  },
  {
    grupo: "Grupo G",
    local: "Nueva Zelanda",
    localScore: null,
    visitante: "Belgica",
    visitanteScore: null,
    fecha: "Sab, 27/6",
    hora: "05:00",
  },
  {
    grupo: "Grupo G",
    local: "Egipto",
    localScore: null,
    visitante: "Iran",
    visitanteScore: null,
    fecha: "Sab, 27/6",
    hora: "05:00",
  },
  {
    grupo: "Grupo L",
    local: "Panama",
    localScore: null,
    visitante: "Inglaterra",
    visitanteScore: null,
    fecha: "Sab, 27/6",
    hora: "23:00",
  },
  {
    grupo: "Grupo L",
    local: "Croacia",
    localScore: null,
    visitante: "Ghana",
    visitanteScore: null,
    fecha: "Sab, 27/6",
    hora: "23:00",
  },
  {
    grupo: "Grupo K",
    local: "Colombia",
    localScore: null,
    visitante: "Portugal",
    visitanteScore: null,
    fecha: "Dom, 28/6",
    hora: "01:30",
  },
  {
    grupo: "Grupo K",
    local: "RD Congo",
    localScore: null,
    visitante: "Uzbekistan",
    visitanteScore: null,
    fecha: "Dom, 28/6",
    hora: "01:30",
  },
  {
    grupo: "Grupo J",
    local: "Argelia",
    localScore: null,
    visitante: "Austria",
    visitanteScore: null,
    fecha: "Dom, 28/6",
    hora: "04:00",
  },
  {
    grupo: "Grupo J",
    local: "Jordania",
    localScore: null,
    visitante: "Argentina",
    visitanteScore: null,
    fecha: "Dom, 28/6",
    hora: "04:00",
  },
];

export default matches;
